language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hdtyler/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true hdtyler/react-test npm run test

after_success:
    - docker build -t hdtyler/multi-client ./client
    - docker build -t hdtyler/multi-nginx ./nginx
    - docker build -t hdtyler/multi-server ./server
    - docker build -t hdtyler/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push hdtyler/multi-client
    - docker push hdtyler/multi-nginx
    - docker push hdtyler/multi-server
    - docker push hdtyler/multi-worker